[package]
name = "whitespace"
version = "0.1.0"
authors = ["zrneely <zrneely@mit.edu>"]

[dependencies]
libc = "*"
memmap2 = "0.5"
nom = "3"

[lib]
name = "wsstd"
path = "src/wsstd.rs"

[[bin]]
name = "whitespace"
path = "src/main.rs"
