[package]
name = "whitespace"
version = "0.1.0"
authors = ["zrneely <zrneely@mit.edu>"]

[dependencies.libc]
version = "*"

[dependencies.nom]
version = "*"
path = "../nom"

[lib]
name = "wsstd"
path = "src/wsstd.rs"

[[bin]]
name = "whitespace"
path = "src/main.rs"
